### PR TITLE
Add educational example

### PR DESCRIPTION
**Pull request by Datseris**
Hi Romain,

So here is the starting script.

I want to remove the polynomial fit in favor of something else. You told me to do such a fit in the arclength coordinate, but I do not know how to do this with `Polynomials`. In fact, I don't think it is even possible.

I want to find a better way to do it, as my `Polynomials` approach fails for 3D systems. I have to read the source code of the predictors in more detail, but not sure when I will have time to delve deep. If you have some spare time before I already finish this, feel free to give me a small paragraph of the tangent method so I can incorporate it here. 

---

P.s.: unrelated with the PR, but I've noticed that the `docs` folder is _full_ of `.png` pictures. All of these will be downloaded by users on `pkg> add`. It stresses even more the importance of using Documenter.jl to build plots, besides the already important reproducibility benefit.

### CODE REVIEW

**Comment by rveltz** [comment]
Hi,

Thank you for the PR!

> I want to remove the polynomial fit in favor of something else. You told me to do such a fit in the arclength coordinate, but I do not know how to do this with Polynomials. In fact, I don't think it is even possible.

Maybe we can just use the secant predictor which is very simple

> P.s.: unrelated with the PR, but I've noticed that the docs folder is full of .png pictures. All of these will be downloaded by users on pkg> add. It stresses even more the importance of using Documenter.jl to build plots, besides the already important reproducibility benefit.

I am aware of this. I started to remove some of the png, it is not finished yet. However, I won't be able to remove all pictures as many tutorials are too extreme (GPU, many cores, computation time...) to be run by the docs builder...

**Comment by Datseris** [comment]
The way I've solved this is to have a repo (same repo that hosts the website of JuliaDYnamics) and host the pngs there. 


> Maybe we can just use the secant predictor which is very simple

Okay, I will need to read up a bit on this as I do not know it. I have found a document.

**Comment by Datseris** [comment]
@rveltz Can you please tell me: the Newton predictor used in BifurcationKit.jl for the Secant method: is it a Newton method in the _mixed_ state space + parameter space, or does it operate only in the state space (fixed point space)?

**Comment by rveltz** [comment]
Your question is a bit ambiguous but I understand your point. Somehow the predictor should not depend on the corrector. t The predictor is basically a way of computing the tangent at (x, p).

That said, you are right, the corrector of the secant method is a Newton method in the mixed state space + parameter space. Indeed, it falls back to https://github.com/rveltz/BifurcationKit.jl/blob/master/src/Predictor.jl#L59 by dispatch.

**Comment by Datseris** [comment]
@rveltz sorry this is slow, but I'm still struggling to make the simplest possible version one can use for education. I'm trying to follow the source code, but I must admit it's much harder than I expected. What I haven't found out yet is the following:

* Where, and how, do you define the "Jacobian", whose inverse needs to be computed for the Newton step?
* Given that this Jacobian is not a square matrix anymore, as it would have one more entry for the parameter derivative, how do you compute the inverse?

If you can give me some light about this two points perhaps I can finalize this... I think the secant predictor, with a corrector that operates on the mixed (state + parameter) space is the way to go for the simplest version.

**Comment by Datseris** [comment]
Hi @rveltz , everything is a-ok now. I've resolved all my problems and have found the simplest possible way one can do a continuation for education purposes. I've already coded it and it seems to work very well. Will update my PR here soon!

**Comment by rveltz** [comment]
Cool!! Thank you

**Comment by Datseris** [comment]
OPS, sorry @rveltz . No this is not ready to merge, I want to do a re-write and a large amount of improvements. Sorry, I had forgotten about this because of the book. Give me a couple of weeks to have the book submitted and I will finish this!

**Comment by Datseris** [comment]
I'm finally back here and will hopefully have this done by the end of the weekend!

**Comment by Datseris** [comment]
@rveltz sorry I'm a bit confused: I merged `master` branch into my PR and all files under `docs` dissapeared... Could please explain :D

**Comment by rveltz** [comment]
Arggg I forgot about this. I followed an old advice of yours, I moved the docs in their own package: https://github.com/bifurcationkit/BifurcationKitDocs.jl

**Comment by Datseris** [comment]
ok I will open a PR there instead.

**Comment by Datseris** [comment]
(by the way I no longer believe that having the docs in a separate package is a good idea. Instead, I believe it is the worst option of the two)

**Comment by rveltz** [comment]
> you can add a new implemented feature in the docs using PR that implements the featu

you can or cannot?

**Comment by Datseris** [comment]
sorry! you cannot!

**Comment by rveltz** [comment]
Can you re-submit to https://github.com/bifurcationkit/BifurcationKitDocs.jl please?

Thank you.

**Pull request closed without merging**
